package dev.apollointhehouse.net.packet

object PacketRegistry {
    private val packetIDToFactory: MutableMap<Int, PacketFactory<*>> = mutableMapOf()
    val classToPacketID: Map<Class<out Packet>, Int> field = mutableMapOf<Class<out Packet>, Int>()

    init {
        register(0, PacketKeepAlive)
        register(1, PacketLogin)
        register(2, PacketHandshake)
        register(3, PacketMessage)
        register(4, PacketSetTime)
        register(5, PacketSetEquippedItem)
        register(6, PacketSetSpawnPosition)
        register(7, PacketEntityInteract)
        register(8, PacketSetHealth)
        register(9, PacketRespawn)
        register(10, PacketMovePlayer)
        register(11, PacketMovePlayer.Pos)
        register(12, PacketMovePlayer.Rot)
        register(13, PacketMovePlayer.PosRot)
        register(14, PacketPlayerAction)
        register(15, PacketUseOrPlaceItemStack)
        register(16, PacketSetCarriedItem)
        register(17, PacketSleep)
        register(18, PacketAnimate)
        register(19, PacketUpdatePlayerState)
        register(20, PacketAddPlayer)
        register(21, PacketAddItemEntity)
        register(22, PacketTakeItemEntity)
        register(23, PacketAddEntity)
        register(24, PacketAddMob)
        register(25, PacketAddPainting)
        register(26, PacketVehicleControl)
        register(27, PacketSetHeldObject)
        register(28, PacketSetEntityMotion)
        register(29, PacketRemoveEntity)
        register(30, PacketMoveEntity)
        register(31, PacketMoveEntity.Pos)
        register(32, PacketMoveEntity.Rot)
        register(33, PacketMoveEntity.PosRot)
        register(34, PacketTeleportEntity)
        register(35, PacketEntityNickname)
        register(36, PacketPlayerConfig)
        register(37, PacketEntityFling)
        register(38, PacketEntityEvent)
        register(39, PacketSetRiding)
        register(40, PacketSetEntityData)
        register(41, PacketPlayerGamemode)
        register(42, PacketEntityTagData)
        register(50, PacketChunkVisibility)
        register(51, PacketBlockRegionUpdate)
        register(52, PacketChunkBlocksUpdate)
        register(53, PacketBlockUpdate)
        register(54, PacketBlockEvent)
        register(60, PacketExplosion)
        register(61, PacketPlaySound)
        register(62, PacketPlaySoundDirect)
        register(63, PacketAddParticle)
        register(70, PacketMessageTranslatable)
        register(71, PacketWeatherEffect)
        register(72, PacketUpdatePlayerProfile)
        register(73, PacketWeatherStatus)
        register(74, PacketGameRule)
        register(75, PacketRecipeSync)
        register(100, PacketContainerOpen)
        register(101, PacketContainerClose)
        register(102, PacketContainerClick)
        register(103, PacketContainerSetSlot)
        register(104, PacketContainerSetContent)
        register(105, PacketContainerSetData)
        register(106, PacketContainerAck)
        register(108, PacketSetHotbarOffset)
        register(120, PacketCommandManager)
        register(121, PacketRequestCommandManager)
        register(130, PacketSignUpdate)
        register(131, PacketMapData)
        register(132, PacketSetMobSpawner)
        register(133, PacketGuidebook)
        register(136, PacketAESSendKey)
        register(137, PacketSetItemName)
        register(138, PacketPlayerList)
        register(139, PacketSetPaintingArt)
        register(140, PacketTileEntityData)
        register(142, PacketFlagOpen)
        register(143, PacketPhotoMode)
        register(200, PacketStatistic)
        register(201, PacketSyncIDs)
        register(250, PacketCustomPayload)
        register(253, PacketServerIcon)
        register(254, PacketPingHandshake)
        register(255, PacketDisconnect)
    }

    inline fun <reified T : Packet> register(id: Int, factory: PacketFactory<T>) {
        register(id, T::class.java, factory)
    }

    fun <T : Packet> register(id: Int, clazz: Class<T>, factory: PacketFactory<T>) {
        require(id !in packetIDToFactory) { "Duplicate packet id: $id" }
        require(clazz !in classToPacketID) { "Duplicate packet: ${clazz.simpleName}" }

        packetIDToFactory[id] = factory
        classToPacketID[clazz] = id
    }

    fun getPacketFactory(id: Int): PacketFactory<*>? = packetIDToFactory[id]
}